/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthedTenantsNewRouteImport } from './routes/_authed/tenants.new'
import { Route as AuthedTenantsSlugRouteImport } from './routes/_authed/tenants.$slug'
import { Route as AuthedTenantsSlugPresetsRouteImport } from './routes/_authed/tenants_.$slug_.presets'
import { Route as AuthedTenantsSlugLocationsRouteImport } from './routes/_authed/tenants_.$slug_.locations'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTenantsNewRoute = AuthedTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsSlugRoute = AuthedTenantsSlugRouteImport.update({
  id: '/tenants/$slug',
  path: '/tenants/$slug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsSlugPresetsRoute =
  AuthedTenantsSlugPresetsRouteImport.update({
    id: '/tenants_/$slug_/presets',
    path: '/tenants/$slug/presets',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTenantsSlugLocationsRoute =
  AuthedTenantsSlugLocationsRouteImport.update({
    id: '/tenants_/$slug_/locations',
    path: '/tenants/$slug/locations',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/tenants/$slug': typeof AuthedTenantsSlugRoute
  '/tenants/new': typeof AuthedTenantsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/tenants/$slug/locations': typeof AuthedTenantsSlugLocationsRoute
  '/tenants/$slug/presets': typeof AuthedTenantsSlugPresetsRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AuthedIndexRoute
  '/tenants/$slug': typeof AuthedTenantsSlugRoute
  '/tenants/new': typeof AuthedTenantsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/tenants/$slug/locations': typeof AuthedTenantsSlugLocationsRoute
  '/tenants/$slug/presets': typeof AuthedTenantsSlugPresetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/tenants/$slug': typeof AuthedTenantsSlugRoute
  '/_authed/tenants/new': typeof AuthedTenantsNewRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/_authed/tenants_/$slug_/locations': typeof AuthedTenantsSlugLocationsRoute
  '/_authed/tenants_/$slug_/presets': typeof AuthedTenantsSlugPresetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/tenants/$slug'
    | '/tenants/new'
    | '/api/auth/callback'
    | '/api/auth/signout'
    | '/tenants/$slug/locations'
    | '/tenants/$slug/presets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/tenants/$slug'
    | '/tenants/new'
    | '/api/auth/callback'
    | '/api/auth/signout'
    | '/tenants/$slug/locations'
    | '/tenants/$slug/presets'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/'
    | '/_authed/tenants/$slug'
    | '/_authed/tenants/new'
    | '/api/auth/callback'
    | '/api/auth/signout'
    | '/_authed/tenants_/$slug_/locations'
    | '/_authed/tenants_/$slug_/presets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tenants/new': {
      id: '/_authed/tenants/new'
      path: '/tenants/new'
      fullPath: '/tenants/new'
      preLoaderRoute: typeof AuthedTenantsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants/$slug': {
      id: '/_authed/tenants/$slug'
      path: '/tenants/$slug'
      fullPath: '/tenants/$slug'
      preLoaderRoute: typeof AuthedTenantsSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants_/$slug_/presets': {
      id: '/_authed/tenants_/$slug_/presets'
      path: '/tenants/$slug/presets'
      fullPath: '/tenants/$slug/presets'
      preLoaderRoute: typeof AuthedTenantsSlugPresetsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants_/$slug_/locations': {
      id: '/_authed/tenants_/$slug_/locations'
      path: '/tenants/$slug/locations'
      fullPath: '/tenants/$slug/locations'
      preLoaderRoute: typeof AuthedTenantsSlugLocationsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedTenantsSlugRoute: typeof AuthedTenantsSlugRoute
  AuthedTenantsNewRoute: typeof AuthedTenantsNewRoute
  AuthedTenantsSlugLocationsRoute: typeof AuthedTenantsSlugLocationsRoute
  AuthedTenantsSlugPresetsRoute: typeof AuthedTenantsSlugPresetsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedTenantsSlugRoute: AuthedTenantsSlugRoute,
  AuthedTenantsNewRoute: AuthedTenantsNewRoute,
  AuthedTenantsSlugLocationsRoute: AuthedTenantsSlugLocationsRoute,
  AuthedTenantsSlugPresetsRoute: AuthedTenantsSlugPresetsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
