/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as FamiliaPaletaRouteImport } from './routes/$familia.$paleta'
import { Route as TSlugDemoRouteImport } from './routes/t/$slug_.demo'
import { Route as TSlugPreviewPresetSlugRouteImport } from './routes/t/$slug_.preview.$presetSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaPaletaRoute = FamiliaPaletaRouteImport.update({
  id: '/$familia/$paleta',
  path: '/$familia/$paleta',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugDemoRoute = TSlugDemoRouteImport.update({
  id: '/t/$slug_/demo',
  path: '/t/$slug/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugPreviewPresetSlugRoute = TSlugPreviewPresetSlugRouteImport.update({
  id: '/t/$slug_/preview/$presetSlug',
  path: '/t/$slug/preview/$presetSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRoute
  '/t/$slug/demo': typeof TSlugDemoRoute
  '/t/$slug/preview/$presetSlug': typeof TSlugPreviewPresetSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRoute
  '/t/$slug/demo': typeof TSlugDemoRoute
  '/t/$slug/preview/$presetSlug': typeof TSlugPreviewPresetSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRoute
  '/t/$slug_/demo': typeof TSlugDemoRoute
  '/t/$slug_/preview/$presetSlug': typeof TSlugPreviewPresetSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$familia/$paleta'
    | '/t/$slug'
    | '/t/$slug/demo'
    | '/t/$slug/preview/$presetSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$familia/$paleta'
    | '/t/$slug'
    | '/t/$slug/demo'
    | '/t/$slug/preview/$presetSlug'
  id:
    | '__root__'
    | '/'
    | '/$familia/$paleta'
    | '/t/$slug'
    | '/t/$slug_/demo'
    | '/t/$slug_/preview/$presetSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliaPaletaRoute: typeof FamiliaPaletaRoute
  TSlugRoute: typeof TSlugRoute
  TSlugDemoRoute: typeof TSlugDemoRoute
  TSlugPreviewPresetSlugRoute: typeof TSlugPreviewPresetSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$familia/$paleta': {
      id: '/$familia/$paleta'
      path: '/$familia/$paleta'
      fullPath: '/$familia/$paleta'
      preLoaderRoute: typeof FamiliaPaletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug_/demo': {
      id: '/t/$slug_/demo'
      path: '/t/$slug/demo'
      fullPath: '/t/$slug/demo'
      preLoaderRoute: typeof TSlugDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug_/preview/$presetSlug': {
      id: '/t/$slug_/preview/$presetSlug'
      path: '/t/$slug/preview/$presetSlug'
      fullPath: '/t/$slug/preview/$presetSlug'
      preLoaderRoute: typeof TSlugPreviewPresetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliaPaletaRoute: FamiliaPaletaRoute,
  TSlugRoute: TSlugRoute,
  TSlugDemoRoute: TSlugDemoRoute,
  TSlugPreviewPresetSlugRoute: TSlugPreviewPresetSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
