/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t/$slug'
import { Route as FamiliaPaletaRouteImport } from './routes/$familia.$paleta'
import { Route as TSlugPresetsRouteImport } from './routes/t/$slug.presets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaPaletaRoute = FamiliaPaletaRouteImport.update({
  id: '/$familia/$paleta',
  path: '/$familia/$paleta',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugPresetsRoute = TSlugPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/presets': typeof TSlugPresetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/presets': typeof TSlugPresetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$familia/$paleta': typeof FamiliaPaletaRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/presets': typeof TSlugPresetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$familia/$paleta' | '/t/$slug' | '/t/$slug/presets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$familia/$paleta' | '/t/$slug' | '/t/$slug/presets'
  id: '__root__' | '/' | '/$familia/$paleta' | '/t/$slug' | '/t/$slug/presets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamiliaPaletaRoute: typeof FamiliaPaletaRoute
  TSlugRoute: typeof TSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$familia/$paleta': {
      id: '/$familia/$paleta'
      path: '/$familia/$paleta'
      fullPath: '/$familia/$paleta'
      preLoaderRoute: typeof FamiliaPaletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/presets': {
      id: '/t/$slug/presets'
      path: '/presets'
      fullPath: '/t/$slug/presets'
      preLoaderRoute: typeof TSlugPresetsRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugPresetsRoute: typeof TSlugPresetsRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugPresetsRoute: TSlugPresetsRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamiliaPaletaRoute: FamiliaPaletaRoute,
  TSlugRoute: TSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
